<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\SourceControl\GitHub\livro-refactoring-with-csharp\Chapter16\Packt.FlightQueryDecoder\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\SourceControl\GitHub\livro-refactoring-with-csharp\Chapter16\Packt.FlightQueryDecoder\.editorconfig" />
  </ItemGroup>

</Project>
